[[session]]
name = "home"
path = "~"

[[session]]
name = "tmux config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/.config/tmux/tmux.conf"

[[session]]
name = "aerospace config"
path = "~/.config/aerospace"
startup_command = "nvim aerospace.toml"
preview_command = "bat --color=always ~/.config/aerospace/aerospace.toml"

[[session]]
name = "zsh config"
path = "~"
startup_command = "nvim .zshrc .zprofile .aliases"
preview_command = "bat --color=always ~/.zshrc"

[[session]]
name = "starship config"
path = "~/.config"
startup_command = "nvim starship.toml"
preview_command = "bat --color=always ~/.config/starship.toml"

[[session]]
name = "tmux sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --color=always ~/.config/sesh/sesh.toml"

[[session]]
name = "ghostty config"
path = "~/.config/ghostty"
startup_command = "nvim config"
preview_command = "bat --color=always ~/.config/ghostty/config"

[[session]]
name = "sketchybar"
path = "~/.config/sketchybar"
startup_command = "nvim .config"
preview_command = "bat --color=always ~/.config/sketchybar/sketchybarrc"

[[session]]
name = "qualifier1"
path = "~/git/qualifier1/"
startup_command = "nvim"
preview_command = "dir ~/git/qualifier1/"

[[session]]
name = "evpn-vxlan"
path = "~/git/qualifier1/evpn-vxlan/"
startup_command = "nvim"
preview_command = "dir ~/git/qualifier1/evpn-vxlan/"

[[session]]
name = "grifter"
path = "~/Developer/grifter"
preview_command = "bat ~/Developer/grifter/README.md"
windows = ["nvim"]

[[window]]
name = "nvim"
startup_command = "nvim"

[[session]]
name = "obsidian"
path = "/Users/dgethings/Library/Mobile Documents/iCloud~md~obsidian/Documents/Main/"
startup_command = "opencode --agent youtube-processor"
